language: csharp
mono: none
sudo: required
dist: bionic
dotnet: 3.0.100
branches:
  only:
    - master
    - develop
script:
  - dotnet build
notifications:
  email:
    on_success: never
    on_failure: always